import React, { useState, useEffect } from "react";
import Nav from "../../components/Nav/Nav";
import CatCard from "../../components/CatCard/CatCard";
import DefaultLayout from "../../layouts/Default";
import Head from "next/head";

const index = () => {
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const [cats, setCats] = useState([]);
  const fetchCats = async () => {
    const response = await fetch("/api/cats");

    const data = await response.json();

    setCats(data);
  };

  // eslint-disable-next-line react-hooks/rules-of-hooks
  useEffect(() => {
    fetchCats();
  }, [cats]);

  return (
    <>
      <Head>
        <title>Cat List</title>{" "}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <div className="container mt-5">
          <div
            style={{
              display: "flex",
              justifyContent: "center",
              flexWrap: "wrap",
              gap: "1.2rem",
            }}
          >
            {cats?.map((cat) => (
              <CatCard key={cat.id} cat={cat} />
            ))}
          </div>
        </div>
      </DefaultLayout>
    </>
  );
};

export default index;
